Logging into Kaggle for the first time can be daunting. Our competitions often have large cash prizes, public leaderboards, and involve complex data. Nevertheless, we really think all data scientists can rapidly learn from machine learning competitions and meaningfully contribute to our community. To give you a clear understanding of how our platform works and a mental model of the type of learning you could do on Kaggle, we've created a Getting Started tutorial for the Titanic competition. It walks you through the initial steps required to get your first decent submission on the leaderboard. By the end of the tutorial, you'll also have a solid understanding of how to use Kaggle's online coding environment, where you'll have trained your own machine learning model.

So if this is your first time entering a Kaggle competition, regardless of whether you:
- have experience with handling large datasets,
- haven't done much coding,
- are newer to data science, or
- are relatively experienced (but are just unfamiliar with Kaggle's platform),

you're in the right place! 

# Part 1: Get started

In this section, you'll learn more about the competition and make your first submission. 

## Join the competition!

The first thing to do is to join the competition!  Open a new window with **[the competition page](https://www.kaggle.com/c/titanic)**, and click on the **"Join Competition"** button, if you haven't already.  (_If you see a "Submit Predictions" button instead of a "Join Competition" button, you have already joined the competition, and don't need to do so again._)

![](https://i.imgur.com/07cskyU.png)

This takes you to the rules acceptance page.  You must accept the competition rules in order to participate.  These rules govern how many submissions you can make per day, the maximum team size, and other competition-specific details.   Then, click on **"I Understand and Accept"** to indicate that you will abide by the competition rules.

## The challenge

The competition is simple: we want you to use the Titanic passenger data (name, age, price of ticket, etc) to try to predict who will survive and who will die.

## The data

To take a look at the competition data, click on the **<a href="https://www.kaggle.com/c/titanic/data" target="_blank" rel="noopener noreferrer"><b>Data tab</b></a>** at the top of the competition page.  Then, scroll down to find the list of files.  
There are three files in the data: (1) **train.csv**, (2) **test.csv**, and (3) **gender_submission.csv**.

### (1) train.csv

**train.csv** contains the details of a subset of the passengers on board (891 passengers, to be exact -- where each passenger gets a different row in the table).  To investigate this data, click on the name of the file on the left of the screen.  Once you've done this, you can view all of the data in the window.  

![](https://i.imgur.com/cYsdt0n.png)

The values in the second column (**"Survived"**) can be used to determine whether each passenger survived or not: 
- if it's a "1", the passenger survived.
- if it's a "0", the passenger died.

For instance, the first passenger listed in **train.csv** is Mr. Owen Harris Braund.  He was 22 years old when he died on the Titanic.

### (2) test.csv

Using the patterns you find in **train.csv**, you have to predict whether the other 418 passengers on board (in **test.csv**) survived.  

Click on **test.csv** (on the left of the screen) to examine its contents.  Note that **test.csv** does not have a **"Survived"** column - this information is hidden from you, and how well you do at predicting these hidden values will determine how highly you score in the competition! 

### (3) gender_submission.csv

The **gender_submission.csv** file is provided as an example that shows how you should structure your predictions.  It predicts that all female passengers survived, and all male passengers died.  Your hypotheses regarding survival will probably be different, which will lead to a different submission file.  But, just like this file, your submission should have:
- a **"PassengerId"** column containing the IDs of each passenger from **test.csv**.
- a **"Survived"** column (that you will create!) with a "1" for the rows where you think the passenger survived, and a "0" where you predict that the passenger died.

# Part 2: Your coding environment

In this section, you'll train your own machine learning model to improve your predictions.  _If you've never written code before or don't have any experience with machine learning, don't worry!  We don't assume any prior experience in this tutorial._

## The Notebook

The first thing to do is to create a Kaggle Notebook where you'll store all of your code.  You can use Kaggle Notebooks to getting up and running with writing code quickly, and without having to install anything on your computer.  (_If you are interested in deep learning, we also offer free GPU access!_) 

Begin by clicking on the **<a href="https://www.kaggle.com/c/titanic/kernels" target="_blank">Code tab</a>** on the competition page.  Then, click on **"New Notebook"**.

![](https://i.imgur.com/v2i82Xd.png)

Your notebook will take a few seconds to load.  In the top left corner, you can see the name of your notebook -- something like **"kernel2daed3cd79"**.

![](https://i.imgur.com/64ZFT1L.png)

You can edit the name by clicking on it.  Change it to something more descriptive, like **"Getting Started with Titanic"**.  

![](https://i.imgur.com/uwyvzXq.png)

## Your first lines of code

When you start a new notebook, it has two gray boxes for storing code.  We refer to these gray boxes as "code cells".

![](https://i.imgur.com/q9mwkZM.png)

The first code cell already has some code in it.  To run this code, put your cursor in the code cell.  (_If your cursor is in the right place, you'll notice a blue vertical line to the left of the gray box._)  Then, either hit the play button (which appears to the left of the blue line), or hit **[Shift] + [Enter]** on your keyboard.

If the code runs successfully, three lines of output are returned.  Below, you can see the same code that you just ran, along with the output that you should see in your notebook.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


This shows us where the competition data is stored, so that we can load the files into the notebook.  We'll do that next.

## Load the data

The second code cell in your notebook now appears below the three lines of output with the file locations.

![](https://i.imgur.com/OQBax9n.png)

Type the two lines of code below into your second code cell.  Then, once you're done, either click on the blue play button, or hit **[Shift] + [Enter]**.  

In [2]:
train_data = pd.read_csv("/kaggle/input/titanic/train.csv")
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
print(train_data.shape)

(891, 12)


In [4]:
train_data.info() #obj 5개

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


5개의 object 데이터에서 Name, Ticket, Cabin 3개의 데이터는 생존 여부와 관련 없으므로 삭제한다.<br>
추가로 PassengerId 또한 같은 이유로 삭제 / Embarked는 세개의 출발지로 나눠 원핫 인코딩을 진행하여 전처리한다.<br>
이는 train, test 데이터를 합친 후 진행한다

In [5]:
train_data = train_data.dropna(subset=['Age'])

print(f"train 데이터에서 {891-len(train_data)}행 삭제")

train 데이터에서 177행 삭제


Your code should return the output above, which corresponds to the first five rows of the table in **train.csv**.  It's very important that you see this output **in your notebook** before proceeding with the tutorial!
> _If your code does not produce this output_, double-check that your code is identical to the two lines above.  And, make sure your cursor is in the code cell before hitting **[Shift] + [Enter]**.

The code that you've just written is in the Python programming language. It uses a Python "module" called **pandas** (abbreviated as `pd`) to load the table from the **train.csv** file into the notebook. To do this, we needed to plug in the location of the file (which we saw was `/kaggle/input/titanic/train.csv`).  
> If you're not already familiar with Python (and pandas), the code shouldn't make sense to you -- but don't worry!  The point of this tutorial is to (quickly!) make your first submission to the competition.  At the end of the tutorial, we suggest resources to continue your learning.

At this point, you should have at least three code cells in your notebook.  
![](https://i.imgur.com/ReLhYca.png)

Copy the code below into the third code cell of your notebook to load the contents of the **test.csv** file.  Don't forget to click on the play button (or hit **[Shift] + [Enter]**)!

In [6]:
test_data = pd.read_csv("/kaggle/input/titanic/test.csv")
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [7]:
print(test_data.shape)

(418, 11)


In [8]:
Ytrain= train_data.pop('Survived')

all_data=pd.concat((train_data, test_data), axis=0)

print(Ytrain.shape)
print(all_data.shape)

(714,)
(1132, 11)


In [9]:
print(Ytrain.sum()/714) #38%생존(train set에서만)

0.4061624649859944


In [10]:
print(all_data[:714].shape) #train데이터
print(all_data[714:].shape) #test데이터

(714, 11)
(418, 11)


As before, make sure that you see the output above in your notebook before continuing.  

Once all of the code runs successfully, all of the data (in **train.csv** and **test.csv**) is loaded in the notebook.  (_The code above shows only the first 5 rows of each table, but all of the data is there -- all 891 rows of **train.csv** and all 418 rows of **test.csv**!_)

# Part 3: Your first submission

Remember our goal: we want to find patterns in **train.csv** that help us predict whether the passengers in **test.csv** survived.

It might initially feel overwhelming to look for patterns, when there's so much data to sort through.  So, we'll start simple.

## Explore a pattern

Remember that the sample submission file in **gender_submission.csv** assumes that all female passengers survived (and all male passengers died).  

Is this a reasonable first guess?  We'll check if this pattern holds true in the data (in **train.csv**).

Copy the code below into a new code cell.  Then, run the cell.

## 3. 전처리 및 결측치 처리 과정

In [11]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1132 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    1132 non-null int64
Pclass         1132 non-null int64
Name           1132 non-null object
Sex            1132 non-null object
Age            1046 non-null float64
SibSp          1132 non-null int64
Parch          1132 non-null int64
Ticket         1132 non-null object
Fare           1131 non-null float64
Cabin          276 non-null object
Embarked       1130 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 106.1+ KB


5개의 object 데이터에서 Name, Ticket, Cabin 3개의 데이터는 생존 여부와 관련 없으므로 삭제한다.

추가로 PassengerId 또한 같은 이유로 삭제 / 

Embarked는 세개의 출발지로 나눠 원핫 인코딩을 진행하여 전처리하려 했으나, 출발지는 딱히 영향을 미칠 것 같지 않으므로 삭제한다

이는 train, test 데이터를 합친 후 진행한다

In [12]:
all_data['Sex'] = all_data['Sex'].replace({'male': 1, 'female': 0})

In [13]:
all_data = all_data.drop(columns = ['PassengerId','Name','Ticket','Cabin','Embarked'])

all_data.shape

(1132, 6)

In [14]:
cols=list(all_data)
for col in list(all_data):
    if (all_data[col].isnull().sum())==0:
        cols.remove(col)
    else:
        pass
print(len(cols))

2


In [15]:
print(cols)

['Age', 'Fare']


In [16]:
for i in cols:
    print(f"{i}에 대한 분석 결과")
    print(all_data[i].describe())
    print("")

Age에 대한 분석 결과
count    1046.000000
mean       29.881138
std        14.413493
min         0.170000
25%        21.000000
50%        28.000000
75%        39.000000
max        80.000000
Name: Age, dtype: float64

Fare에 대한 분석 결과
count    1131.000000
mean       35.038391
std        54.017343
min         0.000000
25%         8.050000
50%        15.033300
75%        32.002050
max       512.329200
Name: Fare, dtype: float64



Age와 Fare 둘 다 중간값으로 넣으면 될 것 같다(50%)

In [17]:
all_data['Age'].median()
all_data['Fare'].median()

15.0333

In [18]:
for col in (cols):
    if col == "Age":
        all_data[col] = all_data[col].fillna(all_data[col].mean())
    else:
        all_data[col] = all_data[col].fillna(all_data[col].median())
    
    
print(f"Total count of missing values in all_data : {all_data.isnull().sum().sum()}")

Total count of missing values in all_data : 0


In [19]:
# clean_train = all_data[:891].dropna(subset=['Age'])

# print(f"train 데이터에서 {len(train_data)-len(clean_train)}행 삭제")

In [20]:
# print(len(clean_train))

In [21]:
# # print(all_data[891:].shape) #test데이터
# # 기존 test데이터와 결측치행을 삭제한 train 데이터셋 병합

# all_data = pd.concat((clean_train, all_data[891:]), axis=0)
# print(len(all_data))

In [22]:
# print(len(all_data[:714])) #train데이터
# print(len(all_data[714:])) #test데이터

In [23]:
# women = train_data.loc[train_data.Sex == 'female']["Survived"]
# rate_women = sum(women)/len(women)

# print("% of women who survived:", rate_women)

Before moving on, make sure that your code returns the output above.  The code above calculates the percentage of female passengers (in **train.csv**) who survived.

Then, run the code below in another code cell:

In [24]:
# men = train_data.loc[train_data.Sex == 'male']["Survived"]
# rate_men = sum(men)/len(men)

# print("% of men who survived:", rate_men)

The code above calculates the percentage of male passengers (in **train.csv**) who survived.

From this you can see that almost 75% of the women on board survived, whereas only 19% of the men lived to tell about it. Since gender seems to be such a strong indicator of survival, the submission file in **gender_submission.csv** is not a bad first guess!

But at the end of the day, this gender-based submission bases its predictions on only a single column.  As you can imagine, by considering multiple columns, we can discover more complex patterns that can potentially yield better-informed predictions.  Since it is quite difficult to consider several columns at once (or, it would take a long time to consider all possible patterns in many different columns simultaneously), we'll use machine learning to automate this for us.

## Your first machine learning model

We'll build what's known as a **random forest model**.  This model is constructed of several "trees" (there are three trees in the picture below, but we'll construct 100!) that will individually consider each passenger's data and vote on whether the individual survived.  Then, the random forest model makes a democratic decision: the outcome with the most votes wins!

![](https://i.imgur.com/AC9Bq63.png)

The code cell below looks for patterns in four different columns (**"Pclass"**, **"Sex"**, **"SibSp"**, and **"Parch"**) of the data.  It constructs the trees in the random forest model based on patterns in the **train.csv** file, before generating predictions for the passengers in **test.csv**.  The code also saves these new predictions in a CSV file **submission.csv**.

Copy this code into your notebook, and run it in a new code cell.

In [25]:
# from sklearn.ensemble import RandomForestClassifier

# y = train_data["Survived"]

# features = ["Pclass", "Sex", "SibSp", "Parch"]
# X = pd.get_dummies(train_data[features])
# X_test = pd.get_dummies(test_data[features])

# model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
# model.fit(X, y)
# predictions = model.predict(X_test)

# output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
# output.to_csv('submission.csv', index=False)
# print("Your submission was successfully saved!")

In [26]:
print(all_data.shape)

(1132, 6)


In [27]:
Xtrain = all_data[:714] #train데이터
Xtest = all_data[714:]  #test데이터

In [28]:
print(all_data)

     Pclass  Sex        Age  SibSp  Parch      Fare
0         3    1  22.000000      1      0    7.2500
1         1    0  38.000000      1      0   71.2833
2         3    0  26.000000      0      0    7.9250
3         1    0  35.000000      1      0   53.1000
4         3    1  35.000000      0      0    8.0500
..      ...  ...        ...    ...    ...       ...
413       3    1  29.881138      0      0    8.0500
414       1    0  39.000000      0      0  108.9000
415       3    1  38.500000      0      0    7.2500
416       3    1  29.881138      0      0    8.0500
417       3    1  29.881138      1      1   22.3583

[1132 rows x 6 columns]


In [29]:
from xgboost import XGBRegressor



model_XGB=XGBRegressor(    
    learning_rate=0.02, n_estimators=600, objective='binary:logistic', silent=True, nthread=1,
#     objective='binary:logistic',  # 이진 분류 로지스틱 회귀
#     eval_metric='error',           # 오분류 오차를 평가 지표로 설정
    min_child_weight = 1,
    gamma = 1,
    max_depth=5,                   # 트리의 최대 깊이
#     learning_rate=0.1,             # 학습률
#     n_estimators=100,              # 트리의 개수
    subsample=0.9,                 # 훈련 데이터의 샘플링 비율
    colsample_bytree=1.0,          # 트리를 만들 때 특성을 샘플링하는 비율
#     random_state=42                # 재현 가능성을 위한 랜덤 시드 설정
)
model_XGB.fit(Xtrain, Ytrain)
XGB_predictions=model_XGB.predict(Xtest)
train_XGB=model_XGB.predict(Xtrain)

/opt/conda/lib/python3.6/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/opt/conda/lib/python3.6/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


In [30]:
# # print(train_XGB)
# # print(np.round(train_XGB[:10], 3))
# train_preds = [1 if x>0.5 else 0 for x in train_XGB]
# print(train_preds)

# #train데이터의 행을 삭제했기 때문에 오류가 발생할 수도 있음

In [31]:
# a=0
# for i in range(len(train_preds)):
#     if Ytrain[i] != train_preds[i]:
#         a+=1

# print(f"두 모델이 다르게 예측한 수는 : {a}") #144개(예측이 나름 많이 다름)

In [32]:
preds = [1 if x>0.5 else 0 for x in XGB_predictions]
print(preds)

[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 

In [33]:
# print(XGB_predictions)

In [34]:
# print(abc)

In [35]:
submission = pd.read_csv("/kaggle/input/titanic/gender_submission.csv")
print(submission)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


In [36]:
a=0
for i in range(len(preds)):
    if submission["Survived"][i] != preds[i]:
        a+=1

print(f"두 모델이 다르게 예측한 수는 : {a}") #18개(예측이 많이 다르진 않음)

#추가 전처리 후 27개로 더 많이 다르게 예측함

#xgboost 하이퍼파라미터 조정 후 다르게 예측한 수는 63으로 눈에 띄게 달라짐
#다시 조정 후 55

#추가 조정 후: 70

두 모델이 다르게 예측한 수는 : 70


In [37]:
submission["Survived"] = preds

In [38]:
print(submission)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


In [39]:
submission.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!


Make sure that your notebook outputs the same message above (`Your submission was successfully saved!`) before moving on.
> Again, don't worry if this code doesn't make sense to you!  For now, we'll focus on how to generate and submit predictions.

Once you're ready, click on the **"Save Version"** button in the top right corner of your notebook.  This will generate a pop-up window.  
- Ensure that the **"Save and Run All"** option is selected, and then click on the **"Save"** button.
- This generates a window in the bottom left corner of the notebook.  After it has finished running, click on the number to the right of the **"Save Version"** button.  This pulls up a list of versions on the right of the screen.  Click on the ellipsis **(...)** to the right of the most recent version, and select **Open in Viewer**.  
- Click on the **Data** tab on the top of the screen.  Then, click on the **"Submit"** button to submit your results.

![](https://i.imgur.com/1ocaUl4.png)

Congratulations for making your first submission to a Kaggle competition!  Within ten minutes, you should receive a message providing your spot on the leaderboard.  Great work!

# Part 4: Learn more!

If you're interested in learning more, we strongly suggest our (3-hour) **[Intro to Machine Learning](https://www.kaggle.com/learn/intro-to-machine-learning)** course, which will help you fully understand all of the code that we've presented here.  You'll also know enough to generate even better predictions!